export const monthList = [
  {
    id: 0,
    name: "January",
    name2: "01",
    year: "2025",
    imageId: "January.jpg",
  },
  {
    id: 1,
    name: "February",
    name2: "02",
    year: "2025",
    imageId: "February.jpg",
  },
  {
    id: 2,
    name: "March",
    name2: "03",
    year: "2025",
    imageId: "March.jpg",
  },
  {
    id: 3,
    name: "April",
    name2: "04",
    year: "2025",
    imageId: "April.jpg",
  },
  {
    id: 4,
    name: "May",
    name2: "05",
    year: "2025",
    imageId: "May.jpg",
  },
  {
    id: 5,
    name: "Jun",
    name2: "06",
    year: "2025",
    imageId: "Jun.jpg",
  },
  {
    id: 6,
    name: "July",
    name2: "07",
    year: "2025",
    imageId: "July.jpg",
  },
  {
    id: 7,
    name: "August",
    name2: "08",
    year: "2025",
    imageId: "August.jpg",
  },
  {
    id: 8,
    name: "September",
    name2: "09",
    year: "2025",
    imageId: "September.jpg",
  },
  {
    id: 9,
    name: "October",
    name2: "10",
    year: "2025",
    imageId: "October.jpg",
  },
  {
    id: 10,
    name: "November",
    name2: "11",
    year: "2025",
    imageId: "November.jpg",
  },
  {
    id: 11,
    name: "December",
    name2: "12",
    year: "2025",
    imageId: "December.jpg",
  },
  {
    id: 12,
    name: "January",
    name2: "01",
    year: "2024",
    imageId: "January_2024.jpg",
  },
  {
    id: 13,
    name: "February",
    name2: "02",
    year: "2024",
    imageId: "February_2024.jpg",
  },
  {
    id: 14,
    name: "March",
    name2: "03",
    year: "2024",
    imageId: "March_2024.jpg",
  },
  {
    id: 15,
    name: "April",
    name2: "04",
    year: "2024",
    imageId: "April_2024.jpg",
  },
  {
    id: 16,
    name: "May",
    name2: "05",
    year: "2024",
    imageId: "May_2024.jpg",
  },
  {
    id: 17,
    name: "Jun",
    name2: "06",
    year: "2024",
    imageId: "Jun_2024.jpg",
  },
  {
    id: 18,
    name: "July",
    name2: "07",
    year: "2024",
    imageId: "July_2024.jpg",
  },
  {
    id: 19,
    name: "August",
    name2: "08",
    year: "2024",
    imageId: "August_2024.jpg",
  },
  {
    id: 20,
    name: "September",
    name2: "09",
    year: "2024",
    imageId: "September_2024.jpg",
  },
  {
    id: 21,
    name: "October",
    name2: "10",
    year: "2024",
    imageId: "October_2024.jpg",
  },
  {
    id: 22,
    name: "November",
    name2: "11",
    year: "2024",
    imageId: "November_2024.jpg",
  },
  {
    id: 23,
    name: "December",
    name2: "12",
    year: "2024",
    imageId: "December_2024.jpg",
  },
];
